### PR TITLE
Remove build from source and streamline install

### PR DESCRIPTION
**Pull request by Itsyuka**
This should hopefully satisfy all needs for now, also a possibility later on to include :UpdateRemotePlugins

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
@brandoncc or @bryall want to give this a try to make sure that this is legit?

Also @Itsyuka have you seen other nvim remote plugins do the same?  Just want to make sure I am doing it somewhat canonical, as this is canonical javascript no cap

**Comment by Itsyuka** [comment]
I've seen other plugins do the exact same thing, some also use curl to pull from the releases instead.

**Comment by bryall** [comment]
agree this is similar to what coc.nvim does

i cannot test the vim-plug command(i use vim's packadd), but i can make sure the install script works on my machine

**Comment by brandoncc** [comment]
@ThePrimeagen I tried to test it, but I can't get rid of the old version of the VimBeGood2 function. I even tried wiping the vim-plug directory. I will try again later today.

**Comment by ThePrimeagen** [comment]
hah, You need to update asap :)

So many improvements!

**Comment by Itsyuka** [comment]
@brandoncc Have you done :UpdateRemotePlugins, it may clear it

**Comment by brandoncc** [comment]
@Itsyuka good call, I was in a hurry so I was using `InstallRemotePlugins` instead.

I have this in my config:

```
Plug 'Itsyuka/vim-be-good', {'branch': 'install-refactor'}
```

I:
- deleted my plugins directory
- ran `:PlugInstall`
- ran `:UpdateRemotePlugins`

I have done this in different orders, but nothing will add the vim be good command back in. I don't think it is installing correctly.

**Comment by bryall** [comment]
@brandoncc  do you have  "{'do': './install.sh'}"? running the script will compile the plugin which UpdateRemotePlugins will then see

**Comment by brandoncc** [comment]
That did it. I changed it to:

```
Plug 'Itsyuka/vim-be-good', {'branch': 'install-refactor', 'do': './install.sh'}
```

Then I deleted my plugins directory, ran `:PlugInstall`, ran `:UpdateRemotePlugins`, and restarted vim.

After that, `:VimBeGood` is working.

Thanks @bryall 

Seems good to me @ThePrimeagen

**Pull request merged**
