### PR TITLE
Endless mode

### PR DESCRIPTION
**Pull request by FL3SH**
Added endless mode for noob level difficulty.

The new game difficulty was introduced in #58. I decided that level may also be an endless practice level.

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
I'll be glad to take a look at this tomorrow morning my friend!!! Thanks SSOOOO MUCH!!!

**Comment by ThePrimeagen** [comment]
Everything is great except for one show stopping issue.  @FL3SH ... :q? You are letting the secret out!!! NO ONE EVER QUITS VIM...

**Comment by brandoncc** [comment]
Congrats @FL3SH !

**Comment by FL3SH** [comment]
Thank you @brandoncc

**Comment by FL3SH** [comment]
@ThePrimeagen I guess if someone went so far to vim-be-good already knows the secret ;)

**Pull request merged**
