### PR TITLE
feat: save round statistics to file

### PR DESCRIPTION
**Pull request by bryall**
First step into addressing #41 

Right now it saves the following into a stats log file in csv format
* localtime
*current round
* difficulty
* round name
* time to complete round

thoughts?

do we want to go json ?  may be easier once luarocks support is builtin into neovim
do we want to have a rolling log of stats?

### CODE REVIEW

**Comment by bryall** [comment]
also addresses #85

**Comment by bryall** [comment]
will need to update README with new option

**Comment by bryall** [comment]
will need to update README with new option

**Comment by ThePrimeagen** [comment]
Great!  This was a huge win.  I want to merge vim-be-good and apm soon.  I want to be able to graph and do all that good stuff to vim-be-good.

**Comment by ThePrimeagen** [comment]
This is a great first step.

**Pull request merged**
