### PR TITLE
Add ci game and helpers

### PR DESCRIPTION
**Pull request by brandoncc**

### CODE REVIEW

**Comment by brandoncc** [comment]
@ThePrimeagen what do you think of the helpers I introduced? Should they have been added at the game level, or are they okay in `GameUtils`?

I think this is ready if you like it.

**Comment by brandoncc** [comment]
@ThePrimeagen what do you think about my last commit? I just saw your mention of the round-based config. The commit feels dirty, since the round is consuming `self.config`, but the lifecycle of that config is actually handled by the game runner. Is the spirit of the commit anywhere near what you were thinking we would be using the round config for? Or did you only plan to use that outside of the round itself?

**Comment by brandoncc** [comment]
@ThePrimeagen merge conflict fixed. I'm a big fan of that games folder change. The structure felt uncomfortable.

**Comment by ThePrimeagen** [comment]
@brandoncc you have another conflict :)

**Comment by brandoncc** [comment]
@ThePrimeagen fixed

**Comment by brandoncc** [comment]
I'm still curious what you think about my questions. If you don't have time, it's okay :-)

**Comment by ThePrimeagen** [comment]
@brandoncc I said it on stream!!! You goose.

There are 2 types of configs.  Game config (difficulty, game types, amount of rounds, etc etc).  Then there are round configs.  Round timings don't have to be the same.  There could be other round configs I haven't thought of yet :)

**Comment by ThePrimeagen** [comment]
Also @brandoncc you have another merge conflict :(  I am sorry.  I merged @bryall before yours :)

**Comment by brandoncc** [comment]
> @brandoncc I said it on stream!!! You goose.
> 
> There are 2 types of configs. Game config (difficulty, game types, amount of rounds, etc etc). Then there are round configs. Round timings don't have to be the same. There could be other round configs I haven't thought of yet :)

I asked this before your stream 😂 Also, I'm curious about my liberal use of `GameUtils` additions. Good? Bad? Appropriate? Inappropriate?

Also, I'd like to point out I added a trim string function that does not use regex, even though that is the recommended solution. I'm not adding regex to one of your projects again 😂

**Comment by brandoncc** [comment]
The branch is mergeable again @ThePrimeagen :-)

**Pull request merged**
