### PR TITLE
Fixed CI

### PR DESCRIPTION
**Pull request by FL3SH**
CI shouldn't fail after a push to README.md

Some fix for CI, at least it's not failing but I am sure someone with better js knowledge could make it better ;)

#45

### CODE REVIEW

**Comment by brandoncc** [comment]
Oh, nice! I didn't see why the failure was happening. Good catch @FL3SH

**Comment by brandoncc** [comment]
Still failing because of the comment in tsconfig.json @FL3SH :-/

**Comment by FL3SH** [comment]
I see, but on my branch, it works.

**Comment by FL3SH** [comment]
I hope #64 fixes this issue.

**Pull request merged**
