### PR TITLE
adding a game for practicing #, and *

### PR DESCRIPTION
**Pull request by anutting**
Ideally, an X would appear underneath where the current cursor is, eliminating the need to /find. Not quite sure how to do that though.

Edit: changed to draft. Looking for input how to make this game better/more fun

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
This seems like a neat idea.  

Let me look at it.

I am curious if this + #44 could be merged and used as macro game. 

To be honest, my only worry is that this game will be to narrow.  Let me play it, play the number game by @bryall and see if there is a possible macro game.

**Comment by anutting** [comment]
I've been learning vim along with your youtube videos and decided to create this game to reinforce a couple important movement keys that I don't use instinctively.

I'm not familiar with macros so I'll defer to your recommendation if you think the game will still remain fun and meet the goal of reinforcing the use of important movement keys.

**Comment by ThePrimeagen** [comment]
That is a good point! How about you fix your merge and I'll get it in

**Comment by anutting** [comment]
@ThePrimeagen I fixed the merge. You may be right, it does feel narrow once I got into it. My game doesn't have that same quick mental decisions that the others have.

**Comment by ThePrimeagen** [comment]
sorry, work is still hurting my feelings.  Will look shortly.

**Comment by anutting** [comment]
There's no rush to merge this. It still feels really close to the relative game. I'm thinking of ways to make it better. I may quadruple the number of lines so that the word you need to jump is off screen and throw in a couple additional random word red herrings to make it more of a challenge.

**Comment by ThePrimeagen** [comment]
I think I am streaming tonight, we will review some PRs!

**Comment by jjant** [comment]
@ThePrimeagen reminder about this :).

**Comment by julianosirtori** [comment]
Do you happen to have any updates on this? 😁

**Comment by anutting** [comment]
I'm closing this as it's pretty stale at this point

**Pull request closed without merging**
