### PR TITLE
Lint fix

### PR DESCRIPTION
**Pull request by FL3SH**
Sorry about that, I didn't know that indentation are so important.

### CODE REVIEW

**Comment by brandoncc** [comment]
I ran prettier and this should be the last one 👍

**Comment by FL3SH** [comment]
`npm run lint:fix` fixed this issue

**Comment by brandoncc** [comment]
We could setup a pre commit hook to run that always...

**Comment by FL3SH** [comment]
@ThePrimeagen @brandoncc are you ok with adding [husky](https://www.npmjs.com/package/husky)

**Comment by brandoncc** [comment]
I'm not sure if a dependency is really needed? https://github.com/git/git/blob/master/templates/hooks--pre-commit.sample

**Comment by FL3SH** [comment]
What about this https://github.com/marketplace/actions/pre-commit, vim-be-good already uses workflows.

**Comment by brandoncc** [comment]
I don't really understand how they work. Does it run locally? If not, I'm not even sure how it would work?

If it does work, I'm fine with it. I imagine Prime would be as well, as long as he is okay with the general idea of using a pre-commit hook. I am not sure his thoughts on git hooks, actually.

**Comment by FL3SH** [comment]
Ok, let's wait for him.

**Comment by ThePrimeagen** [comment]
Nice

**Comment by FL3SH** [comment]
@ThePrimeagen I am very glad that you merged my fix but what about the hook?

**Comment by ThePrimeagen** [comment]
@FL3SH 

I am fine with githooks.  As long as its fast.  Git commit hook is fine.

**Comment by brandoncc** [comment]
@FL3SH I'd say give the Github actions hook a shot and see how it works then. Thanks @ThePrimeagen

**Comment by FL3SH** [comment]
@brandoncc I was playing a little with Github actions hook and I am disappointed. Basically you can just run another action that's will fail if code wasn't properly formated. 
What are the expectation for this hook?

**Comment by brandoncc** [comment]
@FL3SH you know what...I just realized that if prettier alters the files, vim won't update the displayed file automatically. Also, I think that the behavior you described is what the regular pre-commit will do too.

If the fix command is run, and the commit fails, then that would be a signal that more files were updated and need to be staged.

I'm conflicted about where this is worth it or not. Maybe the hook should just run `npm lint` so the committer has to actively do the fix and then re-commit?

**Comment by FL3SH** [comment]
@brandoncc I am still not sure, but what about adding lint as part of npm build?
I think if you are working on a new feature you would probably build your version to test it so my guess is you probably won't' miss a message about broken lint.

**Comment by brandoncc** [comment]
That seems reasonable. I still think that we probably should not have it do `:fix` though, because editors that don't reload on file changes won't update automatically. Basically that means vim :-)

**Comment by FL3SH** [comment]
Ok, do we want to build fail becasue of bad lint
(`"build": "prettier ./src --check && tsc && npm run copy-rplugin-json"`) or continue (`"build": "prettier ./src --check; tsc && npm run copy-rplugin-json"`)  just dispalying the mesage?

**Comment by FL3SH** [comment]
@brandoncc ^ what do you think?

**Comment by brandoncc** [comment]
@FL3SH I think the question is visibility. If the build fails, can we tell? It appears that we would be able to from that snippet, but I want to be sure. If this was on a watch where it builds in the background, visibility would be lower.

I think I prefer the build failure, because...who reads the noise that comes during a build anyway? I only read it if I am debugging something.

**Comment by FL3SH** [comment]
I think this is good enough:
```bash
$ npm run build

> vim-be-good@0.0.1 build /Users/m/workspace/github/vim-be-good
> prettier ./src --check && tsc && npm run copy-rplugin-json

Checking formatting...
src/index.ts
Code style issues found in the above file(s). Forgot to run Prettier?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vim-be-good@0.0.1 build: `prettier ./src --check && tsc && npm run copy-rplugin-json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vim-be-good@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/m/.npm/_logs/2020-06-20T20_50_07_247Z-debug.log
```

**Comment by FL3SH** [comment]
@ThePrimeagen can you share your thoughts about it?

**Pull request merged**
