### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by victorgabr**
This quick-fix can build vim-be-good on windows 10.
Requirements:
[
Git for Windows BASH emulation](https://gitforwindows.org/)
[NodeJs](https://nodejs.org/en/download/)

During PlugInstall call on nvim running on PowerShell, it must call git bash and execute the install.sh script.

### CODE REVIEW

**Comment by brandoncc** [comment]
Thanks for the contribution @victorgabr. I'm curious, doesn't Powershell support forward slashes as a path separator?

Windows is underrepresented in documentation, so thanks again!

**Comment by victorgabr** [comment]
> Thanks for the contribution @victorgabr. I'm curious, doesn't Powershell support forward slashes as a path separator?
> 
> Windows is underrepresented in documentation, so thanks again!

I did not work, the when it calls a script, it does not run on PowerShell, it calls git-bash because *.sh files are associated with it.

**Comment by brandoncc** [comment]
> I did not work, the when it calls a script, it does not run on PowerShell, it calls git-bash because *.sh files are associated with it.

Ah, that makes sense.

Thanks for adding the dependencies to the readme!

**Comment by ThePrimeagen** [comment]
Simply Amazing.

@victorgabr I am just going to trust that whatever you did is correct. I literally don't want to / dont know anything about windows. :)

**Pull request merged**
