### PR TITLE
Add docker instructions

### PR DESCRIPTION
**Pull request by brandoncc**
@ThePrimeagen I thought this was a great idea, so I built it. Anyone can run vim-be-good using:

```bash
docker run -it --rm brandoncc/vim-be-good
```

If they want to make sure they have the latest docker build, they can use:

```bash
docker pull brandoncc/vim-be-good && docker run -it --rm brandoncc/vim-be-good
```

If you would like, I'm happy to transfer ownership of the git and docker repositories to you. Here are the related git repositories:

- https://github.com/brandoncc/docker-vim-be-good
- https://github.com/brandoncc/docker-neovim-master

### CODE REVIEW

**Comment by brandoncc** [comment]
By the way, the docker image comes with batteries, and gruvbox, included 😄 

You can see the vim config that the image uses [here](https://github.com/brandoncc/docker-vim-be-good/blob/master/init.vim).

**Comment by FL3SH** [comment]
I think if we are going for docker it should be built automatically.

**Comment by brandoncc** [comment]
@FL3SH what do you mean? All you have to do is run `docker run -it --rm brandoncc/vim-be-good` and the game opens. Everything is already built in the docker image.

**Comment by FL3SH** [comment]
I mean you should rebuild docker time to time and I think it should be done automatically or you have to add git pull to your entrypoint.

**Comment by brandoncc** [comment]
@FL3SH I still don't understand, can you show me an example of the change you think I should make? I don't understand how we can rebuild the user's images from time to time automatically, but I am up for it if we can. I actually spent hours trying to figure out the best way to handle keeping the user up to date. I started out with just a single Dockerfile in the vim-be-good repo, but that didn't allow me to update the neovim or vim-be-good layers when I wanted to.

**Comment by FL3SH** [comment]
I was thining about something like this:

```dockerfile
FROM debian:stretch-slim
RUN apt-get update && apt-get install --no-install-recommends -qq \
  curl gettext libtool-bin libtool automake pkg-config build-essential \
  ca-certificates git gperf luajit luarocks libuv1-dev libluajit-5.1-dev \
  libunibilium-dev libmsgpack-dev libtermkey-dev libvterm-dev libutf8proc-dev \
  make cmake  \
  && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/neovim/neovim && \
  cd neovim && \
  make CMAKE_BUILD_TYPE=RelWithDebInfo && \
  make install
WORKDIR /usr/src/
RUN curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && git clone https://github.com/ThePrimeagen/vim-be-good
ADD https://raw.githubusercontent.com/brandoncc/docker-vim-be-good/master/init.vim docker/init.vim
RUN nvim -u 'docker/init.vim' +'PlugInstall --sync' +qa
CMD cd /usr/src/vim-be-good && nvim -u 'docker/init.vim' +'PlugInstall --sync' +qa && \
    cd /neovim && git pull &&  make CMAKE_BUILD_TYPE=RelWithDebInfo && make install; \
    nvim -u /usr/src/docker/init.vim -c 'call VimBeGood()'
```

Every time you start docker with `docker run --rm -it fl3sh/vim-be-good` `vim-be-good` and `neovim` will be updated.

You can also skip update with `docker run --rm -it --entrypoint nvim fl3sh/vim-be-good -u /usr/src/docker/init.vim -c 'call VimBeGood()'`

Btw my docker is a little bit smaller ;)
```bash
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
fl3sh/vim-be-good       latest              b8c55708ac05        15 minutes ago      869MB
brandoncc/vim-be-good   latest              f84de4ddd85a        4 hours ago         2.05GB
```

I really don't like this hacky approach for docker, I think we should build a new one every successful push to master and it must be a part of Github workflows.

**Comment by brandoncc** [comment]
@FL3SH I'm 99.99999999999% sure that your dockerfile will _not_ update anything automatically. Docker caches each step, and only re-runs the steps if the Dockerfile changes. That is why I spent hours coming up with a good solution. You can verify this by changing your init.vim and running your container again. Your changes will not be reflected until you rebuild.

If you look at my docker files, you will see I already do all of those steps. The one big advantage you have is you installed a cmake package and I compiled it. I read the docs and it said I could use a snap or compile it...I didn't think to just try apt 😂

I will update mine, and I will also switch to a slim image. I used the `node` image because I figured that was the easiest way to get node in the container, but stretch-slim must have node.

Thanks, and I'm happy to be proven wrong on any of this.

**Comment by brandoncc** [comment]
@FL3SH I just realized it doesn't need node anymore, good catch :-)

**Comment by FL3SH** [comment]
> @FL3SH I'm 99.99999999999% sure that your dockerfile will _not_ update anything automatically. Docker caches each step, and only re-runs the steps if the Dockerfile changes. That is why I spent hours coming up with a good solution. You can verify this by changing your init.vim and running your container again. Your changes will not be reflected until you rebuild.

I think you miss my point. I totally agree with `init.vim`, but you could always `wget` it from a remote source in your docker `CMD` like this `CMD wget https://raw.githubusercontent.com/brandoncc/docker-vim-be-good/master/init.vim`, so when you start your docker this wget command will get a new version of your init.vim.

I've done sth similar for both git repos.

**Comment by ThePrimeagen** [comment]
@brandoncc as stated earlier, I am unable to review any of these changes, so let me know when its ready to be merged.  

Earliest i'll review changes will be sunday night / monday night!

**Comment by brandoncc** [comment]
@ThePrimeagen since the PR is just instructions, you can actually merge if you want.

**Comment by brandoncc** [comment]
@FL3SH I see what you are saying, but wouldn't the `CMD` step would still be a cached layer? I don't think the get would be executed every time...

**Comment by brandoncc** [comment]
@FL3SH I just got an idea from yours. You are updating neovim in every docker run, which takes way too long (that is one of the things that is nice about the docker images)...but that is an excellent way to deal with updating vim-be-good automatically.

I do want people to be able to play offline though, so I think I will check if the user can ping github first, and if they can't, then open the game they already have.

@ThePrimeagen I take that back....I'm going to update the PR in a few minutes before you merge.

**Comment by brandoncc** [comment]
@ThePrimeagen last ping, it is ready to merge. I integrated some of @FL3SH's input, and I hope to integrate more of it later (to add auto-updates of vim-be-good...although that could get added to the game itself).

**Pull request merged**
